name: Build and Deploy

on:
  workflow_dispatch:  # Manueller Trigger

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [21]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  # Zweiter Job: GitHub Release und Deployment
  deploy-gh:
    name: Deploy to GitHub
    runs-on: ubuntu-22.04
    needs: build  # Der Deploy-Job wird nur ausgeführt, wenn der Build-Job erfolgreich war
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts

      - name: Extract version from JAR filename
        id: extract_version
        run: |
          JAR_FILE=$(ls *.jar | grep -E 'anti-creeper-.*\.jar' | head -n 1)
          VERSION=${JAR_FILE#anti-creeper-}
          VERSION=${VERSION/-sources/}
          VERSION=${VERSION%.jar}
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: "Release ${{ steps.extract_version.outputs.version }}"
          body: "Beschreibung des Releases"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          for file in *.jar; do
            gh release upload "${{ steps.create_release.outputs.id }}" "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Modrinth
    runs-on: ubuntu-22.04
    needs: build  # Der Deploy-Job wird nur ausgeführt, wenn der Build-Job erfolgreich war
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
      
      - name: Extract version from JAR filename
        id: extract_version
        run: |
          JAR_FILE=$(ls *.jar | grep -E 'anti-creeper-.*\.jar' | head -n 1)
          VERSION=${JAR_FILE#anti-creeper-}
          VERSION=${VERSION/-sources/}
          VERSION=${VERSION%.jar}
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Deploy to modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Uqqp9wzq
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version: ${{ steps.extract_version.outputs.version }}
          files: |
            *-@(dev|sources|javadoc).jar
          
